import unittest

from scripts.generate_supabase_sql import generate_sql


class GenerateSupabaseSqlTest(unittest.TestCase):
    def test_generates_isolated_idempotent_schema_without_operational_rows(self):
        sql = generate_sql().lower()
        self.assertIn("create schema if not exists estadias", sql)
        self.assertIn("set local search_path to estadias", sql)
        self.assertIn("create table if not exists mod_estadias_lcte_normalizada", sql)
        self.assertIn("create table if not exists mod_estadias_cruzamento_inicial", sql)
        self.assertIn("generated by default as identity", sql)
        self.assertIn("create unique index if not exists idx_mod_estadias_config_chave", sql)
        self.assertNotIn("autoincrement", sql)
        self.assertNotIn("delete from", sql)
        self.assertNotIn("drop table", sql)
        self.assertTrue(sql.rstrip().endswith("commit;"))


if __name__ == "__main__":
    unittest.main()
