"""Generate the temporary PostgreSQL-compatible schema from current migrations.

The output contains structure and built-in settings only, never operational rows.
"""

import re
import sqlite3
from pathlib import Path

from src.database.migrations import create_modular_tables


OUTPUT = Path(__file__).with_name("estadias_supabase_inicial.sql")


def generate_sql() -> str:
    conn = sqlite3.connect(":memory:")
    conn.row_factory = sqlite3.Row
    try:
        create_modular_tables(conn)
        objects = conn.execute(
            "select type, name, sql from sqlite_master "
            "where type in ('table', 'index') and sql is not null and name != 'sqlite_sequence' "
            "order by case type when 'table' then 0 else 1 end, rowid"
        ).fetchall()
        settings = conn.execute("select chave, valor, descricao, updated_at, updated_by from mod_estadias_configuracoes order by chave").fetchall()
    finally:
        conn.close()

    lines = [
        "-- Estrutura inicial de compatibilidade. Executar no SQL Editor do projeto Supabase novo.",
        "-- Nao copia ou apaga registros antigos. Reexecutavel; nao usar em outro projeto.",
        "begin;",
        "create schema if not exists estadias;",
        "set local search_path to estadias;",
    ]
    table_count = 0
    for item in objects:
        statement = item["sql"]
        if item["type"] == "table":
            table_count += 1
            statement = re.sub(r"(?i)^create table\s+", "create table if not exists ", statement, count=1)
            statement = re.sub(r"(?i)integer primary key autoincrement", "bigint generated by default as identity primary key", statement)
        else:
            statement = re.sub(r"(?i)^create (unique )?index\s+", lambda match: f"create {match.group(1) or ''}index if not exists ", statement, count=1)
        lines.append(statement.rstrip().rstrip(";") + ";")

    def literal(value) -> str:
        return "'" + str(value or "").replace("'", "''") + "'"

    for row in settings:
        values = ", ".join(literal(row[key]) for key in row.keys())
        key = literal(row["chave"])
        lines.append(
            "insert into mod_estadias_configuracoes (chave, valor, descricao, updated_at, updated_by) "
            f"select {values} where not exists "
            f"(select 1 from mod_estadias_configuracoes where chave = {key});"
        )
    lines.extend([
        f"do $$ begin if (select count(*) from information_schema.tables where table_schema = 'estadias') < {table_count} "
        "then raise exception 'Estrutura Estadias incompleta'; end if; end $$;",
        "commit;",
    ])
    return "\n\n".join(lines) + "\n"


if __name__ == "__main__":
    OUTPUT.write_text(generate_sql(), encoding="utf-8")
    print(f"SQL gerado: {OUTPUT} (somente estrutura e configuracoes padrao).")
